//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RipleMaticNETTest.Servicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicio.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRegistrar_Ingreso_Ripleymatico", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getRegistrar_Ingreso_Ripleymatico(string id_sucursal, string id_kiosco, string nro_documento, int tip_documento, string nro_tarjeta, int tip_tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VALIDAR_TARJETA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] VALIDAR_TARJETA(string sNumeroTarjeta, string sCodigoKiosko);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OBTENER_CONFIGURACION_KIOSKO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] OBTENER_CONFIGURACION_KIOSKO(string sIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LLamarMetodoParaValidarTarjeta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string LLamarMetodoParaValidarTarjeta(string sCuenta, string sMetodo, string DataMonitor, bool esRipleymatico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarTipoTarjetaPorBinn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        RipleMaticNETTest.Servicio.OpcionesTarjeta BuscarTipoTarjetaPorBinn(string sBinnTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SAVE_LOG_CONSULTAS_COMISIONES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string SAVE_LOG_CONSULTAS_COMISIONES(string ID_SUCURSAL, string NOMBRE_KIOSCO, string OPCION, string CODIGO_EMPLEADO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EjemploSuperEfectivo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        RipleMaticNETTest.Servicio.SuperEfectivo EjemploSuperEfectivo(string sBinnTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EjemploSuperEfectivoParametros", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        RipleMaticNETTest.Servicio.Parametros EjemploSuperEfectivoParametros(string sBinnTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VALIDAR_DNI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string VALIDAR_DNI(string idTipoTarjeta, string tipoDocumento, string numeroDocumento, string dataMonitor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTarjetasParaDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        RipleMaticNETTest.Servicio.TipoTarjeta[] ObtenerTarjetasParaDocumento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarReenganche", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string VerificarReenganche(string tipoProducto, string tipoDocumento, string numeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarDesembolso", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string VerificarDesembolso(string tipoProducto, string tipoDocumento, string numeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerOfertaSEF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string ObtenerOfertaSEF(string tipoProducto, string tipoDocumento, string numeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerSucursalBanco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string ObtenerSucursalBanco(string codigoKiosko);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PRUEBA_CONEXION_SQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string PRUEBA_CONEXION_SQL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OBTENER_VARIABLES_TIMEOUT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string OBTENER_VARIABLES_TIMEOUT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BUSCAR_COD_SUCURSAL_BANCO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string BUSCAR_COD_SUCURSAL_BANCO(string sIDSucursalKiosco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BUSCAR_ID_KIOSCO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string BUSCAR_ID_KIOSCO(string sNombreKiosco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BUSCAR_DATOS_SIMULADOR_OFERTA_SEF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string BUSCAR_DATOS_SIMULADOR_OFERTA_SEF(string sTasaTEM, string sNroTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SAVE_LOG_CONSULTAS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string SAVE_LOG_CONSULTAS(string ID_SUCURSAL, string NOMBRE_KIOSCO, string ID_MENU, string TIPO_TARJETA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SAVE_LOG_CONSULTAS_SEF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string SAVE_LOG_CONSULTAS_SEF(string sCodSucursalBanco, string sCodigoKiosco, string sTipoDocumento, string sNroDocumento, string sOpcion, string sCodigoAtencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VALIDAR_DNI_CLASICA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string VALIDAR_DNI_CLASICA(string sNroDNI, string sDATA_MONITOR_KIOSCO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VALIDAR_DOC_ASOCIADOS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string VALIDAR_DOC_ASOCIADOS(string sNDocumento, string sDATA_MONITOR_KIOSCO, string sTProducto, string sTDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VALIDAR_DOC_ASOCIADOS_MC_VISA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string VALIDAR_DOC_ASOCIADOS_MC_VISA(string sTProducto, string sTDocumento, string sNDocumento, string sDATA_MONITOR_KIOSCO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VALIDAR_CARNET_EXTRANJERIA_CLASICA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string VALIDAR_CARNET_EXTRANJERIA_CLASICA(string sNroCarnet, string sDATA_MONITOR_KIOSCO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VALIDAR_TARJETA_CLASICA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        RipleMaticNETTest.Servicio.Respuesta VALIDAR_TARJETA_CLASICA(string NroTarjeta, string sDATA_MONITOR_KIOSCO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VALIDAR_TARJETA_ABIERTA_RSAT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        RipleMaticNETTest.Servicio.Respuesta VALIDAR_TARJETA_ABIERTA_RSAT(string NroTarjeta, string sDATA_MONITOR_KIOSCO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SALDO_TARJETA_CLASICA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string SALDO_TARJETA_CLASICA(string sNroTarjeta, string sNroCuenta, string sCodKiosco, string sDATA_MONITOR_KIOSCO, RipleMaticNETTest.Servicio.TServidor Servidor, string sMigrado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MOVIMIENTOS_CLASICA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string MOVIMIENTOS_CLASICA(string sNroTarjeta, string sNroCuenta, string sDATA_MONITOR_KIOSCO, RipleMaticNETTest.Servicio.TServidor Servidor, string sMigrado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SALDO_TARJETA_ASOCIADA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        RipleMaticNETTest.Servicio.Respuesta SALDO_TARJETA_ASOCIADA(string sNroTarjeta, string sDATA_MONITOR_KIOSCO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MOVIMIENTOS_ASOCIADA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string MOVIMIENTOS_ASOCIADA(string sNroTarjeta, string sDATA_MONITOR_KIOSCO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ESTADO_CUENTA_CLASICA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string ESTADO_CUENTA_CLASICA(string sNroTarjeta, string sNroCuenta, string sDATA_MONITOR_KIOSCO, RipleMaticNETTest.Servicio.TServidor SERVIDOR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ESTADO_CUENTA_ASOCIADOS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string ESTADO_CUENTA_ASOCIADOS(string sNroTarjeta, string sNroCuenta, string sDATA_MONITOR_KIOSCO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ESTADO_CUENTA_CLASICA_RSAT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string ESTADO_CUENTA_CLASICA_RSAT(string sNroTarjeta, string sNroCuenta, string sDATA_MONITOR_KIOSCO, RipleMaticNETTest.Servicio.TServidor Servidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SIMULADOR_DEPOSITO_PLAZO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string SIMULADOR_DEPOSITO_PLAZO(string sMoneda, string sMonto, string sPlazoDias, string sDATA_MONITOR_KIOSCO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SIMULADOR_OFERTA_SUPEREFECTIVO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string SIMULADOR_OFERTA_SUPEREFECTIVO(string sTarjeta, string sTasaTEM, string sMonto, string sPlazoMeses, string sMontoOfertado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SIMULADOR_OFERTA_SUPEREFECTIVO_TEST", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string SIMULADOR_OFERTA_SUPEREFECTIVO_TEST(string sTarjeta, string sTasaTEM, string sMonto, string sPlazoMeses, string sMontoOfertado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SIMULADOR_OFERTA_SEF_VALIDADO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string SIMULADOR_OFERTA_SEF_VALIDADO(string sTipoProducto, string sTipoDocumento, string sNroDocumento, string sTarjeta, string sTasaTEM, string sMonto, string sPlazoMeses);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SIMULADOR_OFERTA_SEF_ACEPTADO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string SIMULADOR_OFERTA_SEF_ACEPTADO(string sTipoProducto, string sTipoDocumento, string sNroDocumento, string sMonto, string sPlazoMeses, string sTasaTCEA, string sCuota, string sUsuario, string codigoSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CONSOLIDADO_CLIENTE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string CONSOLIDADO_CLIENTE(string sTipoProducto, string sNroTarjeta, string sNroCuenta, string sDNI, string sDATA_MONITOR_KIOSCO, RipleMaticNETTest.Servicio.TServidor Servidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CONSULTA_DEPOSITO_PLAZO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string CONSULTA_DEPOSITO_PLAZO(string sDNI, string sDATA_MONITOR_KIOSCO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CONSULTA_CUENTA_AHORROS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string CONSULTA_CUENTA_AHORROS(string sDNI, string sDATA_MONITOR_KIOSCO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CONSULTA_PRESTAMO_EFECTIVO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string CONSULTA_PRESTAMO_EFECTIVO(string sDNI, string sDATA_MONITOR_KIOSCO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CONSULTA_RIPLEY_PUNTOS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string CONSULTA_RIPLEY_PUNTOS(string sTipoTarjeta, string sNroTarjeta, string sNRO_CUENTA, string sDATA_MONITOR_KIOSCO, RipleMaticNETTest.Servicio.TServidor Servidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FUN_PUNTOS_ACTIVOS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string FUN_PUNTOS_ACTIVOS(string sNroTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CONSULTA_SUPER_EFECTIVO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string CONSULTA_SUPER_EFECTIVO(string sDATA_MONITOR_KIOSCO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OBTENER_PROMOCIONES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] OBTENER_PROMOCIONES(string tipoProducto, string tipoDocumento, string nroDocumento, string nroContrato, string tipoTarjeta, string linea_actual, string nro_tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MOSTRAR_SUPEREFECTIVO_SEF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string MOSTRAR_SUPEREFECTIVO_SEF(string sTipoProducto, string sTipoDocumento, string sNroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MOSTRAR_INCREMENTO_LINEA_INC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        RipleMaticNETTest.Servicio.Salida MOSTRAR_INCREMENTO_LINEA_INC(string nroContrato, string tipoTarjeta, string linea_actual, string nro_tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ACTUALIZAR_OFERTA_SUPEREFECTIVO_SEF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string ACTUALIZAR_OFERTA_SUPEREFECTIVO_SEF(string sDataParametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ACTUALIZAR_OFERTA_INCREMENTO_LINEA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        RipleMaticNETTest.Servicio.Salida ACTUALIZAR_OFERTA_INCREMENTO_LINEA(string nroContrato, double codigoSucursal, string nroCaja, double nroTransaccion, string nroTarjeta, string nombreCliente, double lineaInicial, double lineaEgm, double lineaCons, double lineaEfex, string fechaInicioVigencia, string fechaFinVigencia, string tipoTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SAVE_LOG_CONSULTAS_INC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        bool SAVE_LOG_CONSULTAS_INC(double codigoSucursalBanco, string codigoKiosko, double codigoTipoDocumento, string nroDocumento, string opcion, int codigoAtencion, string numeroTarjeta, string tipoSistema, string lineaInicial, string lineaFinal, string inicioVigencia, string finVigencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OBTENER_FACTOR_ITF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        double OBTENER_FACTOR_ITF();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PRUEBA_CONEXION_ORA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string PRUEBA_CONEXION_ORA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PRUEBA_CONEXION_ORA_SEF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string PRUEBA_CONEXION_ORA_SEF();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PRUEBA_CONEXION_ORA_INC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string PRUEBA_CONEXION_ORA_INC();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CONSULTA_CTS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string CONSULTA_CTS(string sDNI, string sDATA_MONITOR_KIOSCO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CONSULTAR_DOC_MC_VISA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string CONSULTAR_DOC_MC_VISA(string sNroTarjeta, ref string Nro_Contrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CONSULTAR_DOC_MC_VISA_ORI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string CONSULTAR_DOC_MC_VISA_ORI(string sNroTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATOS_GIF_CARD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConfiguracionKiosko))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string DATOS_GIF_CARD(string sNumero, string sOpcion, string sDATA_MONITOR_KIOSCO);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Salida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int existeField;
        
        private string promocionField;
        
        private string nroTarjetaField;
        
        private string nroDocumentoField;
        
        private string nombreClienteField;
        
        private double lineaInicialField;
        
        private double lineaEgmField;
        
        private double lineaConsField;
        
        private double lineaEfexField;
        
        private string fechaInicioVigenciaField;
        
        private string fechaFinVigenciaField;
        
        private double okField;
        
        private int codigoAtencionField;
        
        private string codeField;
        
        private string mensajeField;
        
        private string mensajeImpresionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Existe {
            get {
                return this.existeField;
            }
            set {
                this.existeField = value;
                this.RaisePropertyChanged("Existe");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Promocion {
            get {
                return this.promocionField;
            }
            set {
                this.promocionField = value;
                this.RaisePropertyChanged("Promocion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NroTarjeta {
            get {
                return this.nroTarjetaField;
            }
            set {
                this.nroTarjetaField = value;
                this.RaisePropertyChanged("NroTarjeta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                this.nroDocumentoField = value;
                this.RaisePropertyChanged("NroDocumento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                this.nombreClienteField = value;
                this.RaisePropertyChanged("NombreCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double LineaInicial {
            get {
                return this.lineaInicialField;
            }
            set {
                this.lineaInicialField = value;
                this.RaisePropertyChanged("LineaInicial");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double LineaEgm {
            get {
                return this.lineaEgmField;
            }
            set {
                this.lineaEgmField = value;
                this.RaisePropertyChanged("LineaEgm");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double LineaCons {
            get {
                return this.lineaConsField;
            }
            set {
                this.lineaConsField = value;
                this.RaisePropertyChanged("LineaCons");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double LineaEfex {
            get {
                return this.lineaEfexField;
            }
            set {
                this.lineaEfexField = value;
                this.RaisePropertyChanged("LineaEfex");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FechaInicioVigencia {
            get {
                return this.fechaInicioVigenciaField;
            }
            set {
                this.fechaInicioVigenciaField = value;
                this.RaisePropertyChanged("FechaInicioVigencia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string FechaFinVigencia {
            get {
                return this.fechaFinVigenciaField;
            }
            set {
                this.fechaFinVigenciaField = value;
                this.RaisePropertyChanged("FechaFinVigencia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double Ok {
            get {
                return this.okField;
            }
            set {
                this.okField = value;
                this.RaisePropertyChanged("Ok");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int CodigoAtencion {
            get {
                return this.codigoAtencionField;
            }
            set {
                this.codigoAtencionField = value;
                this.RaisePropertyChanged("CodigoAtencion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string MensajeImpresion {
            get {
                return this.mensajeImpresionField;
            }
            set {
                this.mensajeImpresionField = value;
                this.RaisePropertyChanged("MensajeImpresion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Respuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estadoField;
        
        private string cadenaField;
        
        private string mensajeField;
        
        private string codigoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Cadena {
            get {
                return this.cadenaField;
            }
            set {
                this.cadenaField = value;
                this.RaisePropertyChanged("Cadena");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TipoTarjeta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nombreTarjetaField;
        
        private int tipoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreTarjeta {
            get {
                return this.nombreTarjetaField;
            }
            set {
                this.nombreTarjetaField = value;
                this.RaisePropertyChanged("NombreTarjeta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Parametros : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sCodigoOficinaField;
        
        private string sTerminalFisicoField;
        
        private string sCodigoCanalField;
        
        private string sCodUsuarioField;
        
        private string sNombreClienteField;
        
        private string sTipoDocumentoField;
        
        private string sNumeroDocumentoField;
        
        private string sTipoProductoField;
        
        private string sCodigoEntidadField;
        
        private string sCentroAltaField;
        
        private string sCuentaField;
        
        private string nMontoAceptadoField;
        
        private string nPlazoMesField;
        
        private string nCuotaMesField;
        
        private string nTEAField;
        
        private string nTEMField;
        
        private string sMonedaField;
        
        private string sFechaVencimientoField;
        
        private string sCanalField;
        
        private string sSucursalField;
        
        private string sCodigoVendedorField;
        
        private string sCodigoUsuarioField;
        
        private string sCodigoAtencionField;
        
        private string sAplicaITFField;
        
        private string sIndicadorCommitField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sCodigoOficina {
            get {
                return this.sCodigoOficinaField;
            }
            set {
                this.sCodigoOficinaField = value;
                this.RaisePropertyChanged("sCodigoOficina");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sTerminalFisico {
            get {
                return this.sTerminalFisicoField;
            }
            set {
                this.sTerminalFisicoField = value;
                this.RaisePropertyChanged("sTerminalFisico");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sCodigoCanal {
            get {
                return this.sCodigoCanalField;
            }
            set {
                this.sCodigoCanalField = value;
                this.RaisePropertyChanged("sCodigoCanal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sCodUsuario {
            get {
                return this.sCodUsuarioField;
            }
            set {
                this.sCodUsuarioField = value;
                this.RaisePropertyChanged("sCodUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sNombreCliente {
            get {
                return this.sNombreClienteField;
            }
            set {
                this.sNombreClienteField = value;
                this.RaisePropertyChanged("sNombreCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sTipoDocumento {
            get {
                return this.sTipoDocumentoField;
            }
            set {
                this.sTipoDocumentoField = value;
                this.RaisePropertyChanged("sTipoDocumento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sNumeroDocumento {
            get {
                return this.sNumeroDocumentoField;
            }
            set {
                this.sNumeroDocumentoField = value;
                this.RaisePropertyChanged("sNumeroDocumento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string sTipoProducto {
            get {
                return this.sTipoProductoField;
            }
            set {
                this.sTipoProductoField = value;
                this.RaisePropertyChanged("sTipoProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string sCodigoEntidad {
            get {
                return this.sCodigoEntidadField;
            }
            set {
                this.sCodigoEntidadField = value;
                this.RaisePropertyChanged("sCodigoEntidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string sCentroAlta {
            get {
                return this.sCentroAltaField;
            }
            set {
                this.sCentroAltaField = value;
                this.RaisePropertyChanged("sCentroAlta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string sCuenta {
            get {
                return this.sCuentaField;
            }
            set {
                this.sCuentaField = value;
                this.RaisePropertyChanged("sCuenta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string nMontoAceptado {
            get {
                return this.nMontoAceptadoField;
            }
            set {
                this.nMontoAceptadoField = value;
                this.RaisePropertyChanged("nMontoAceptado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string nPlazoMes {
            get {
                return this.nPlazoMesField;
            }
            set {
                this.nPlazoMesField = value;
                this.RaisePropertyChanged("nPlazoMes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string nCuotaMes {
            get {
                return this.nCuotaMesField;
            }
            set {
                this.nCuotaMesField = value;
                this.RaisePropertyChanged("nCuotaMes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string nTEA {
            get {
                return this.nTEAField;
            }
            set {
                this.nTEAField = value;
                this.RaisePropertyChanged("nTEA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string nTEM {
            get {
                return this.nTEMField;
            }
            set {
                this.nTEMField = value;
                this.RaisePropertyChanged("nTEM");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string sMoneda {
            get {
                return this.sMonedaField;
            }
            set {
                this.sMonedaField = value;
                this.RaisePropertyChanged("sMoneda");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string sFechaVencimiento {
            get {
                return this.sFechaVencimientoField;
            }
            set {
                this.sFechaVencimientoField = value;
                this.RaisePropertyChanged("sFechaVencimiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string sCanal {
            get {
                return this.sCanalField;
            }
            set {
                this.sCanalField = value;
                this.RaisePropertyChanged("sCanal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string sSucursal {
            get {
                return this.sSucursalField;
            }
            set {
                this.sSucursalField = value;
                this.RaisePropertyChanged("sSucursal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string sCodigoVendedor {
            get {
                return this.sCodigoVendedorField;
            }
            set {
                this.sCodigoVendedorField = value;
                this.RaisePropertyChanged("sCodigoVendedor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string sCodigoUsuario {
            get {
                return this.sCodigoUsuarioField;
            }
            set {
                this.sCodigoUsuarioField = value;
                this.RaisePropertyChanged("sCodigoUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string sCodigoAtencion {
            get {
                return this.sCodigoAtencionField;
            }
            set {
                this.sCodigoAtencionField = value;
                this.RaisePropertyChanged("sCodigoAtencion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string sAplicaITF {
            get {
                return this.sAplicaITFField;
            }
            set {
                this.sAplicaITFField = value;
                this.RaisePropertyChanged("sAplicaITF");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string sIndicadorCommit {
            get {
                return this.sIndicadorCommitField;
            }
            set {
                this.sIndicadorCommitField = value;
                this.RaisePropertyChanged("sIndicadorCommit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SuperEfectivo : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OpcionesTarjeta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nroTarjetaField;
        
        private string nombreTarjetaField;
        
        private int binnField;
        
        private string tipoField;
        
        private string tipoTarjetaPasadaField;
        
        private string metodoWsCallField;
        
        private string esTitularField;
        
        private string nroCuentaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NroTarjeta {
            get {
                return this.nroTarjetaField;
            }
            set {
                this.nroTarjetaField = value;
                this.RaisePropertyChanged("NroTarjeta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreTarjeta {
            get {
                return this.nombreTarjetaField;
            }
            set {
                this.nombreTarjetaField = value;
                this.RaisePropertyChanged("NombreTarjeta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Binn {
            get {
                return this.binnField;
            }
            set {
                this.binnField = value;
                this.RaisePropertyChanged("Binn");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TipoTarjetaPasada {
            get {
                return this.tipoTarjetaPasadaField;
            }
            set {
                this.tipoTarjetaPasadaField = value;
                this.RaisePropertyChanged("TipoTarjetaPasada");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MetodoWsCall {
            get {
                return this.metodoWsCallField;
            }
            set {
                this.metodoWsCallField = value;
                this.RaisePropertyChanged("MetodoWsCall");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string EsTitular {
            get {
                return this.esTitularField;
            }
            set {
                this.esTitularField = value;
                this.RaisePropertyChanged("EsTitular");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string NroCuenta {
            get {
                return this.nroCuentaField;
            }
            set {
                this.nroCuentaField = value;
                this.RaisePropertyChanged("NroCuenta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfiguracionKiosko : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nombreField;
        
        private string serverField;
        
        private string server_SimuladorField;
        
        private string server_PrintField;
        
        private string server_ComField;
        
        private string bin1Field;
        
        private int longitud_Tarjeta_Bin1Field;
        
        private int posini_Bin1Field;
        
        private int longitud_Bin_Bin1Field;
        
        private string bin2Field;
        
        private int longitud_Tarjeta_Bin2Field;
        
        private int posini_Bin2Field;
        
        private int longitud_Bin_Bin2Field;
        
        private string codigo_SucursalField;
        
        private string codigo_KioskoField;
        
        private string iD_KioskoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
                this.RaisePropertyChanged("Server");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Server_Simulador {
            get {
                return this.server_SimuladorField;
            }
            set {
                this.server_SimuladorField = value;
                this.RaisePropertyChanged("Server_Simulador");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Server_Print {
            get {
                return this.server_PrintField;
            }
            set {
                this.server_PrintField = value;
                this.RaisePropertyChanged("Server_Print");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Server_Com {
            get {
                return this.server_ComField;
            }
            set {
                this.server_ComField = value;
                this.RaisePropertyChanged("Server_Com");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Bin1 {
            get {
                return this.bin1Field;
            }
            set {
                this.bin1Field = value;
                this.RaisePropertyChanged("Bin1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Longitud_Tarjeta_Bin1 {
            get {
                return this.longitud_Tarjeta_Bin1Field;
            }
            set {
                this.longitud_Tarjeta_Bin1Field = value;
                this.RaisePropertyChanged("Longitud_Tarjeta_Bin1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Posini_Bin1 {
            get {
                return this.posini_Bin1Field;
            }
            set {
                this.posini_Bin1Field = value;
                this.RaisePropertyChanged("Posini_Bin1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Longitud_Bin_Bin1 {
            get {
                return this.longitud_Bin_Bin1Field;
            }
            set {
                this.longitud_Bin_Bin1Field = value;
                this.RaisePropertyChanged("Longitud_Bin_Bin1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Bin2 {
            get {
                return this.bin2Field;
            }
            set {
                this.bin2Field = value;
                this.RaisePropertyChanged("Bin2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Longitud_Tarjeta_Bin2 {
            get {
                return this.longitud_Tarjeta_Bin2Field;
            }
            set {
                this.longitud_Tarjeta_Bin2Field = value;
                this.RaisePropertyChanged("Longitud_Tarjeta_Bin2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int Posini_Bin2 {
            get {
                return this.posini_Bin2Field;
            }
            set {
                this.posini_Bin2Field = value;
                this.RaisePropertyChanged("Posini_Bin2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int Longitud_Bin_Bin2 {
            get {
                return this.longitud_Bin_Bin2Field;
            }
            set {
                this.longitud_Bin_Bin2Field = value;
                this.RaisePropertyChanged("Longitud_Bin_Bin2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Codigo_Sucursal {
            get {
                return this.codigo_SucursalField;
            }
            set {
                this.codigo_SucursalField = value;
                this.RaisePropertyChanged("Codigo_Sucursal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Codigo_Kiosko {
            get {
                return this.codigo_KioskoField;
            }
            set {
                this.codigo_KioskoField = value;
                this.RaisePropertyChanged("Codigo_Kiosko");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ID_Kiosko {
            get {
                return this.iD_KioskoField;
            }
            set {
                this.iD_KioskoField = value;
                this.RaisePropertyChanged("ID_Kiosko");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TServidor {
        
        /// <comentarios/>
        SICRON,
        
        /// <comentarios/>
        RSAT,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : RipleMaticNETTest.Servicio.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<RipleMaticNETTest.Servicio.ServiceSoap>, RipleMaticNETTest.Servicio.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getRegistrar_Ingreso_Ripleymatico(string id_sucursal, string id_kiosco, string nro_documento, int tip_documento, string nro_tarjeta, int tip_tarjeta) {
            return base.Channel.getRegistrar_Ingreso_Ripleymatico(id_sucursal, id_kiosco, nro_documento, tip_documento, nro_tarjeta, tip_tarjeta);
        }
        
        public object[] VALIDAR_TARJETA(string sNumeroTarjeta, string sCodigoKiosko) {
            return base.Channel.VALIDAR_TARJETA(sNumeroTarjeta, sCodigoKiosko);
        }
        
        public object[] OBTENER_CONFIGURACION_KIOSKO(string sIP) {
            return base.Channel.OBTENER_CONFIGURACION_KIOSKO(sIP);
        }
        
        public string LLamarMetodoParaValidarTarjeta(string sCuenta, string sMetodo, string DataMonitor, bool esRipleymatico) {
            return base.Channel.LLamarMetodoParaValidarTarjeta(sCuenta, sMetodo, DataMonitor, esRipleymatico);
        }
        
        public RipleMaticNETTest.Servicio.OpcionesTarjeta BuscarTipoTarjetaPorBinn(string sBinnTarjeta) {
            return base.Channel.BuscarTipoTarjetaPorBinn(sBinnTarjeta);
        }
        
        public string SAVE_LOG_CONSULTAS_COMISIONES(string ID_SUCURSAL, string NOMBRE_KIOSCO, string OPCION, string CODIGO_EMPLEADO) {
            return base.Channel.SAVE_LOG_CONSULTAS_COMISIONES(ID_SUCURSAL, NOMBRE_KIOSCO, OPCION, CODIGO_EMPLEADO);
        }
        
        public RipleMaticNETTest.Servicio.SuperEfectivo EjemploSuperEfectivo(string sBinnTarjeta) {
            return base.Channel.EjemploSuperEfectivo(sBinnTarjeta);
        }
        
        public RipleMaticNETTest.Servicio.Parametros EjemploSuperEfectivoParametros(string sBinnTarjeta) {
            return base.Channel.EjemploSuperEfectivoParametros(sBinnTarjeta);
        }
        
        public string VALIDAR_DNI(string idTipoTarjeta, string tipoDocumento, string numeroDocumento, string dataMonitor) {
            return base.Channel.VALIDAR_DNI(idTipoTarjeta, tipoDocumento, numeroDocumento, dataMonitor);
        }
        
        public RipleMaticNETTest.Servicio.TipoTarjeta[] ObtenerTarjetasParaDocumento() {
            return base.Channel.ObtenerTarjetasParaDocumento();
        }
        
        public string VerificarReenganche(string tipoProducto, string tipoDocumento, string numeroDocumento) {
            return base.Channel.VerificarReenganche(tipoProducto, tipoDocumento, numeroDocumento);
        }
        
        public string VerificarDesembolso(string tipoProducto, string tipoDocumento, string numeroDocumento) {
            return base.Channel.VerificarDesembolso(tipoProducto, tipoDocumento, numeroDocumento);
        }
        
        public string ObtenerOfertaSEF(string tipoProducto, string tipoDocumento, string numeroDocumento) {
            return base.Channel.ObtenerOfertaSEF(tipoProducto, tipoDocumento, numeroDocumento);
        }
        
        public string ObtenerSucursalBanco(string codigoKiosko) {
            return base.Channel.ObtenerSucursalBanco(codigoKiosko);
        }
        
        public string PRUEBA_CONEXION_SQL() {
            return base.Channel.PRUEBA_CONEXION_SQL();
        }
        
        public string OBTENER_VARIABLES_TIMEOUT() {
            return base.Channel.OBTENER_VARIABLES_TIMEOUT();
        }
        
        public string BUSCAR_COD_SUCURSAL_BANCO(string sIDSucursalKiosco) {
            return base.Channel.BUSCAR_COD_SUCURSAL_BANCO(sIDSucursalKiosco);
        }
        
        public string BUSCAR_ID_KIOSCO(string sNombreKiosco) {
            return base.Channel.BUSCAR_ID_KIOSCO(sNombreKiosco);
        }
        
        public string BUSCAR_DATOS_SIMULADOR_OFERTA_SEF(string sTasaTEM, string sNroTarjeta) {
            return base.Channel.BUSCAR_DATOS_SIMULADOR_OFERTA_SEF(sTasaTEM, sNroTarjeta);
        }
        
        public string SAVE_LOG_CONSULTAS(string ID_SUCURSAL, string NOMBRE_KIOSCO, string ID_MENU, string TIPO_TARJETA) {
            return base.Channel.SAVE_LOG_CONSULTAS(ID_SUCURSAL, NOMBRE_KIOSCO, ID_MENU, TIPO_TARJETA);
        }
        
        public string SAVE_LOG_CONSULTAS_SEF(string sCodSucursalBanco, string sCodigoKiosco, string sTipoDocumento, string sNroDocumento, string sOpcion, string sCodigoAtencion) {
            return base.Channel.SAVE_LOG_CONSULTAS_SEF(sCodSucursalBanco, sCodigoKiosco, sTipoDocumento, sNroDocumento, sOpcion, sCodigoAtencion);
        }
        
        public string VALIDAR_DNI_CLASICA(string sNroDNI, string sDATA_MONITOR_KIOSCO) {
            return base.Channel.VALIDAR_DNI_CLASICA(sNroDNI, sDATA_MONITOR_KIOSCO);
        }
        
        public string VALIDAR_DOC_ASOCIADOS(string sNDocumento, string sDATA_MONITOR_KIOSCO, string sTProducto, string sTDocumento) {
            return base.Channel.VALIDAR_DOC_ASOCIADOS(sNDocumento, sDATA_MONITOR_KIOSCO, sTProducto, sTDocumento);
        }
        
        public string VALIDAR_DOC_ASOCIADOS_MC_VISA(string sTProducto, string sTDocumento, string sNDocumento, string sDATA_MONITOR_KIOSCO) {
            return base.Channel.VALIDAR_DOC_ASOCIADOS_MC_VISA(sTProducto, sTDocumento, sNDocumento, sDATA_MONITOR_KIOSCO);
        }
        
        public string VALIDAR_CARNET_EXTRANJERIA_CLASICA(string sNroCarnet, string sDATA_MONITOR_KIOSCO) {
            return base.Channel.VALIDAR_CARNET_EXTRANJERIA_CLASICA(sNroCarnet, sDATA_MONITOR_KIOSCO);
        }
        
        public RipleMaticNETTest.Servicio.Respuesta VALIDAR_TARJETA_CLASICA(string NroTarjeta, string sDATA_MONITOR_KIOSCO) {
            return base.Channel.VALIDAR_TARJETA_CLASICA(NroTarjeta, sDATA_MONITOR_KIOSCO);
        }
        
        public RipleMaticNETTest.Servicio.Respuesta VALIDAR_TARJETA_ABIERTA_RSAT(string NroTarjeta, string sDATA_MONITOR_KIOSCO) {
            return base.Channel.VALIDAR_TARJETA_ABIERTA_RSAT(NroTarjeta, sDATA_MONITOR_KIOSCO);
        }
        
        public string SALDO_TARJETA_CLASICA(string sNroTarjeta, string sNroCuenta, string sCodKiosco, string sDATA_MONITOR_KIOSCO, RipleMaticNETTest.Servicio.TServidor Servidor, string sMigrado) {
            return base.Channel.SALDO_TARJETA_CLASICA(sNroTarjeta, sNroCuenta, sCodKiosco, sDATA_MONITOR_KIOSCO, Servidor, sMigrado);
        }
        
        public string MOVIMIENTOS_CLASICA(string sNroTarjeta, string sNroCuenta, string sDATA_MONITOR_KIOSCO, RipleMaticNETTest.Servicio.TServidor Servidor, string sMigrado) {
            return base.Channel.MOVIMIENTOS_CLASICA(sNroTarjeta, sNroCuenta, sDATA_MONITOR_KIOSCO, Servidor, sMigrado);
        }
        
        public RipleMaticNETTest.Servicio.Respuesta SALDO_TARJETA_ASOCIADA(string sNroTarjeta, string sDATA_MONITOR_KIOSCO) {
            return base.Channel.SALDO_TARJETA_ASOCIADA(sNroTarjeta, sDATA_MONITOR_KIOSCO);
        }
        
        public string MOVIMIENTOS_ASOCIADA(string sNroTarjeta, string sDATA_MONITOR_KIOSCO) {
            return base.Channel.MOVIMIENTOS_ASOCIADA(sNroTarjeta, sDATA_MONITOR_KIOSCO);
        }
        
        public string ESTADO_CUENTA_CLASICA(string sNroTarjeta, string sNroCuenta, string sDATA_MONITOR_KIOSCO, RipleMaticNETTest.Servicio.TServidor SERVIDOR) {
            return base.Channel.ESTADO_CUENTA_CLASICA(sNroTarjeta, sNroCuenta, sDATA_MONITOR_KIOSCO, SERVIDOR);
        }
        
        public string ESTADO_CUENTA_ASOCIADOS(string sNroTarjeta, string sNroCuenta, string sDATA_MONITOR_KIOSCO) {
            return base.Channel.ESTADO_CUENTA_ASOCIADOS(sNroTarjeta, sNroCuenta, sDATA_MONITOR_KIOSCO);
        }
        
        public string ESTADO_CUENTA_CLASICA_RSAT(string sNroTarjeta, string sNroCuenta, string sDATA_MONITOR_KIOSCO, RipleMaticNETTest.Servicio.TServidor Servidor) {
            return base.Channel.ESTADO_CUENTA_CLASICA_RSAT(sNroTarjeta, sNroCuenta, sDATA_MONITOR_KIOSCO, Servidor);
        }
        
        public string SIMULADOR_DEPOSITO_PLAZO(string sMoneda, string sMonto, string sPlazoDias, string sDATA_MONITOR_KIOSCO) {
            return base.Channel.SIMULADOR_DEPOSITO_PLAZO(sMoneda, sMonto, sPlazoDias, sDATA_MONITOR_KIOSCO);
        }
        
        public string SIMULADOR_OFERTA_SUPEREFECTIVO(string sTarjeta, string sTasaTEM, string sMonto, string sPlazoMeses, string sMontoOfertado) {
            return base.Channel.SIMULADOR_OFERTA_SUPEREFECTIVO(sTarjeta, sTasaTEM, sMonto, sPlazoMeses, sMontoOfertado);
        }
        
        public string SIMULADOR_OFERTA_SUPEREFECTIVO_TEST(string sTarjeta, string sTasaTEM, string sMonto, string sPlazoMeses, string sMontoOfertado) {
            return base.Channel.SIMULADOR_OFERTA_SUPEREFECTIVO_TEST(sTarjeta, sTasaTEM, sMonto, sPlazoMeses, sMontoOfertado);
        }
        
        public string SIMULADOR_OFERTA_SEF_VALIDADO(string sTipoProducto, string sTipoDocumento, string sNroDocumento, string sTarjeta, string sTasaTEM, string sMonto, string sPlazoMeses) {
            return base.Channel.SIMULADOR_OFERTA_SEF_VALIDADO(sTipoProducto, sTipoDocumento, sNroDocumento, sTarjeta, sTasaTEM, sMonto, sPlazoMeses);
        }
        
        public string SIMULADOR_OFERTA_SEF_ACEPTADO(string sTipoProducto, string sTipoDocumento, string sNroDocumento, string sMonto, string sPlazoMeses, string sTasaTCEA, string sCuota, string sUsuario, string codigoSucursal) {
            return base.Channel.SIMULADOR_OFERTA_SEF_ACEPTADO(sTipoProducto, sTipoDocumento, sNroDocumento, sMonto, sPlazoMeses, sTasaTCEA, sCuota, sUsuario, codigoSucursal);
        }
        
        public string CONSOLIDADO_CLIENTE(string sTipoProducto, string sNroTarjeta, string sNroCuenta, string sDNI, string sDATA_MONITOR_KIOSCO, RipleMaticNETTest.Servicio.TServidor Servidor) {
            return base.Channel.CONSOLIDADO_CLIENTE(sTipoProducto, sNroTarjeta, sNroCuenta, sDNI, sDATA_MONITOR_KIOSCO, Servidor);
        }
        
        public string CONSULTA_DEPOSITO_PLAZO(string sDNI, string sDATA_MONITOR_KIOSCO) {
            return base.Channel.CONSULTA_DEPOSITO_PLAZO(sDNI, sDATA_MONITOR_KIOSCO);
        }
        
        public string CONSULTA_CUENTA_AHORROS(string sDNI, string sDATA_MONITOR_KIOSCO) {
            return base.Channel.CONSULTA_CUENTA_AHORROS(sDNI, sDATA_MONITOR_KIOSCO);
        }
        
        public string CONSULTA_PRESTAMO_EFECTIVO(string sDNI, string sDATA_MONITOR_KIOSCO) {
            return base.Channel.CONSULTA_PRESTAMO_EFECTIVO(sDNI, sDATA_MONITOR_KIOSCO);
        }
        
        public string CONSULTA_RIPLEY_PUNTOS(string sTipoTarjeta, string sNroTarjeta, string sNRO_CUENTA, string sDATA_MONITOR_KIOSCO, RipleMaticNETTest.Servicio.TServidor Servidor) {
            return base.Channel.CONSULTA_RIPLEY_PUNTOS(sTipoTarjeta, sNroTarjeta, sNRO_CUENTA, sDATA_MONITOR_KIOSCO, Servidor);
        }
        
        public string FUN_PUNTOS_ACTIVOS(string sNroTarjeta) {
            return base.Channel.FUN_PUNTOS_ACTIVOS(sNroTarjeta);
        }
        
        public string CONSULTA_SUPER_EFECTIVO(string sDATA_MONITOR_KIOSCO) {
            return base.Channel.CONSULTA_SUPER_EFECTIVO(sDATA_MONITOR_KIOSCO);
        }
        
        public object[] OBTENER_PROMOCIONES(string tipoProducto, string tipoDocumento, string nroDocumento, string nroContrato, string tipoTarjeta, string linea_actual, string nro_tarjeta) {
            return base.Channel.OBTENER_PROMOCIONES(tipoProducto, tipoDocumento, nroDocumento, nroContrato, tipoTarjeta, linea_actual, nro_tarjeta);
        }
        
        public string MOSTRAR_SUPEREFECTIVO_SEF(string sTipoProducto, string sTipoDocumento, string sNroDocumento) {
            return base.Channel.MOSTRAR_SUPEREFECTIVO_SEF(sTipoProducto, sTipoDocumento, sNroDocumento);
        }
        
        public RipleMaticNETTest.Servicio.Salida MOSTRAR_INCREMENTO_LINEA_INC(string nroContrato, string tipoTarjeta, string linea_actual, string nro_tarjeta) {
            return base.Channel.MOSTRAR_INCREMENTO_LINEA_INC(nroContrato, tipoTarjeta, linea_actual, nro_tarjeta);
        }
        
        public string ACTUALIZAR_OFERTA_SUPEREFECTIVO_SEF(string sDataParametros) {
            return base.Channel.ACTUALIZAR_OFERTA_SUPEREFECTIVO_SEF(sDataParametros);
        }
        
        public RipleMaticNETTest.Servicio.Salida ACTUALIZAR_OFERTA_INCREMENTO_LINEA(string nroContrato, double codigoSucursal, string nroCaja, double nroTransaccion, string nroTarjeta, string nombreCliente, double lineaInicial, double lineaEgm, double lineaCons, double lineaEfex, string fechaInicioVigencia, string fechaFinVigencia, string tipoTarjeta) {
            return base.Channel.ACTUALIZAR_OFERTA_INCREMENTO_LINEA(nroContrato, codigoSucursal, nroCaja, nroTransaccion, nroTarjeta, nombreCliente, lineaInicial, lineaEgm, lineaCons, lineaEfex, fechaInicioVigencia, fechaFinVigencia, tipoTarjeta);
        }
        
        public bool SAVE_LOG_CONSULTAS_INC(double codigoSucursalBanco, string codigoKiosko, double codigoTipoDocumento, string nroDocumento, string opcion, int codigoAtencion, string numeroTarjeta, string tipoSistema, string lineaInicial, string lineaFinal, string inicioVigencia, string finVigencia) {
            return base.Channel.SAVE_LOG_CONSULTAS_INC(codigoSucursalBanco, codigoKiosko, codigoTipoDocumento, nroDocumento, opcion, codigoAtencion, numeroTarjeta, tipoSistema, lineaInicial, lineaFinal, inicioVigencia, finVigencia);
        }
        
        public double OBTENER_FACTOR_ITF() {
            return base.Channel.OBTENER_FACTOR_ITF();
        }
        
        public string PRUEBA_CONEXION_ORA() {
            return base.Channel.PRUEBA_CONEXION_ORA();
        }
        
        public string PRUEBA_CONEXION_ORA_SEF() {
            return base.Channel.PRUEBA_CONEXION_ORA_SEF();
        }
        
        public string PRUEBA_CONEXION_ORA_INC() {
            return base.Channel.PRUEBA_CONEXION_ORA_INC();
        }
        
        public string CONSULTA_CTS(string sDNI, string sDATA_MONITOR_KIOSCO) {
            return base.Channel.CONSULTA_CTS(sDNI, sDATA_MONITOR_KIOSCO);
        }
        
        public string CONSULTAR_DOC_MC_VISA(string sNroTarjeta, ref string Nro_Contrato) {
            return base.Channel.CONSULTAR_DOC_MC_VISA(sNroTarjeta, ref Nro_Contrato);
        }
        
        public string CONSULTAR_DOC_MC_VISA_ORI(string sNroTarjeta) {
            return base.Channel.CONSULTAR_DOC_MC_VISA_ORI(sNroTarjeta);
        }
        
        public string DATOS_GIF_CARD(string sNumero, string sOpcion, string sDATA_MONITOR_KIOSCO) {
            return base.Channel.DATOS_GIF_CARD(sNumero, sOpcion, sDATA_MONITOR_KIOSCO);
        }
    }
}
